# ================= CONFIG =================

import os

TOKEN = os.getenv("BOT_TOKEN")
MONGO_URL = os.getenv("MONGO_URL")

ADMIN_ID = 5565826679

BOT_USERNAME = "Gezxbot"

FORCE_CHANNEL_ID = -1003791438228
FORCE_CHANNEL_LINK = "https://t.me/+SZWfXlte9ddkMTJl"

STORAGE_CHANNEL_ID = -1003832061830

SEARCH_GROUP_LINK = "https://t.me/+0sWBTplLi4s3ODM9"

# IMAGES
START_IMAGE = "AgACAgUAAxkBAAENYRVqOpupBOgdQVbsSVV7fouyjTLCJQACExFrG3yt2FU5YdLDNbZmbAEAAwIAA3cAAzwE"
HELP_IMAGE = "AgACAgUAAxkBAAENYRhqOpwQnzrbNn2aX4FomOuuWmRJTAACFBFrG3yt2FXgRNU82rCpgQEAAwIAA3cAAzwE"
ABOUT_IMAGE = "AgACAgUAAxkBAAENYRtqOp03AAGARotIFIscylOumS1NI00AAiERaxt8rdhVLkXhKfT5uc4BAAMCAAN3AAM8BA"
